import React, { useState, useCallback, useEffect, useRef } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export async function getServerSideProps(context) {

  return {
    props: {}
  }
}

export default function Home() {
  const ref = useRef()
  const [loading, setLoading] = useState(false)
  const [url, setUrl] = useState(null)

  const sendData = useCallback(async () => {
    const data = ref.current.value

    if (data) {
      setLoading(true)
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ data })
      })
      const json = await res.json()
      setLoading(false)
      ref.current.value = ''
      setUrl(json.url)
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <h1>
          Welcome to QRArt
        </h1>

        <section className="nes-container with-title">
          <h3 className="title">Your data</h3>
          <textarea ref={ref} id="qr_data" cols="30" rows="2" className="nes-textarea" />
          <button className="nes-btn is-primary" onClick={sendData}>Generate</button>
        </section>

        {url && <section className="nes-container with-title">
          <h3 className="title">Your QR code</h3>
          <img src={url} alt="QR" />
        </section>
        }


      </main>
    </div>
  )
}
