import React, { useState, useCallback, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getServerSideProps(context) {
  return {
    props: {},
  };
}

export default function Home() {
  const ref = useRef();
  const [loading, setLoading] = useState(false);
  const [url, setUrl] = useState(null);

  const sendData = useCallback(async () => {
    const data = ref.current.value;

    if (data) {
      setLoading(true);
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ data }),
      });
      const json = await res.json();
      setLoading(false);
      ref.current.value = "";
      setUrl(json.url);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Press+Start+2P"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <h1>Welcome to QRArt</h1>
        </header>

        <div className={styles.content}>
          <section className="topic">
            <h2 id="1">
              <a href="#1">#</a>
              Topic 1
            </h2>
            <p>Text 1</p>
          </section>

          <section className="topic">
            <h2 id="2">
              <a href="#2">#</a>
              Topic 1
            </h2>
            <p>Text 1</p>
          </section>

          <section className="topic">
            <h2 id="3">
              <a href="#3">#</a>
              Topic 1
            </h2>
            <p>Text 1</p>
          </section>

          <section className="message-left">
            <i className="nes-bcrikko"></i>
            <p className="nes-balloon nes-pointer from-left">Some text</p>
          </section>

          <section className="nes-container with-title section">
            <h3 className="title">Your data</h3>
            <textarea
              ref={ref}
              id="qr_data"
              cols="30"
              rows="2"
              className="nes-textarea"
            />
            <button className="nes-btn is-primary" onClick={sendData}>
              Generate
            </button>
          </section>

          {url && (
            <section className="nes-container with-title section">
              <h3 className="title">Your QR code</h3>
              <img src={url} alt="QR" />
            </section>
          )}
        </div>
      </main>
    </div>
  );
}
